- saber/sequence_processor.py
When a model is saved using `SequenceProcessor.save()`, the configuration used to train that model as an `.ini` file is saved in the saved model folder.
This simply involved adding a call to `Config.save()`.
Closes #26.
> Additionally save config file when saving a model

- README.md
- saber/config.py
- saber/constants.py
- saber/dataset.py
- saber/models/multi_task_lstm_crf.py
- saber/preprocessor.py
- saber/sequence_processor.py
- saber/tests/test_config.py
- saber/utils/generic_utils.py
- saber/utils/model_utils.py
With this pull request you can now perform transfer learning as follows:
```python
from saber.sequence_processor import SequenceProcessor
sp = SequenceProcessor()
sp.load('path/to/pretrained_models/PRGE')
sp.load_dataset('datasets/CRAFT')
sp.fit()
```
This is the simplest implementation I could think up.
**TODOS**
**Changed**
**Resources**
- [This](https://machinelearningmastery.com/save-load-keras-deep-learning-models/) blog on saving and loading keras models
Closes #29 & closes #30.
> Implement transfer learning

- README.md
- docs/index.md
- docs/installation.md
- docs/quick_start.md
- mkdocs.yml
- notebooks/lightning_tour.ipynb
- requirements.txt
- saber/app.py
- saber/preprocessor.py
- saber/sequence_processor.py
- saber/tests/test_preprocessor.py
- saber/utils/generic_utils.py
This pull request adds coreference resolution by using the Spacy model trained and provided by [NeuralCoref](https://github.com/huggingface/neuralcoref). This allows Saber to handle, for example, the following situation:
_"We identify the **scaffold p62/SQSTM1 protein** as a novel VANGL2-binding partner and show **its** key role in an evolutionarily conserved VANGL2–p62/SQSTM1–JNK pathway"_
by resolving "**its**" to "**scaffold p62/SQSTM1 protein**". This should improve performance in downstream tasks like relation extraction. 
Closes #43.
> Add coreference

- requirements.txt
- setup.py
The relative ordering of dependencies in `requirements.txt` and `setup.py` meant that spacy wasn't actually being installed. Fixed!
> Fix issue that resulting in spacy install being skipped

- notebooks/lightning_tour.ipynb
- saber/preprocessor.py
- saber/tests/test_text_utils.py
- saber/utils/text_utils.py
This pull request adds a small modification to the default Spacy tokenizer in order to more closely match the tokenization scheme of the data the model was trained on. This should lead to better performance downstream.
Essentially, the only change is that the tokenizer is now much more fine-grained. All alphanumeric sequences are preserved a single tokens, but everything else is split into single-character tokens (e.g. '-', '/', etc are all split).
> Adding better tokenization of biomedical entities

- docs/installation.md
- setup.cfg
- setup.py
Small pull request that allows you to install saber and run the test suit from a cloned repository all in one go:
```
git clone https://github.com/BaderLab/saber.git
cd saber
python setup.py test
```
Installing this way allows you to verify the install went smoothly.
Closes #37.
> Allow for installation with test suite check

- saber/utils/grounding_utils.py
Removed useless/shallow "copying" of the annotation dict; fixed duplicate text.
> Polishing (of grounding utils)

- saber/saber.py
Previously, when loading a pre-trained model, i.e.
```python
from saber.saber import Saber
saber = Saber()
saber.load('PRGE')
```
The user had to provide the same model "name" (referring to its architecture) of the pre-trained model via the `model_name` argument in the config file. This pull request makes it implicit by saving the model name and loading it when the pre-trained model is loaded.
Closes #63.
> User no longer has to provide name of pre-trained models architecture

- Dockerfile
- saber/config.py
- saber/constants.py
- saber/models/multi_task_lstm_crf.py
- saber/saber.py
- saber/tests/test_base_model.py
- saber/tests/test_config.py
- saber/tests/test_saber.py
Fixes an issue where a config file (`*.ini`) had no effect when passed as a command line argument (`config_filepath`). A config passed at the command line now takes precedence over the default config file.
Closes #19.
> User can now specify config filepath at command line

- .travis.yml
The TravisCI builds all fail with a cryptic error message. 
Closes #81.
> Fix broken TravisCI config

- .travis.yml
- saber/tests/test_config.py
- saber/tests/test_data_utils.py
- saber/tests/test_generic_utils.py
- saber/tests/test_metrics.py
- saber/tests/test_model_utils.py
- setup.py
Essentially just involves updating the `setup.py` file. But for future reference, when using the `tmpdir` pytest fixture, make sure to use `tmpdir.strpath` to actually access the string version of the filepath. For some reason, using just `tmdir` on its own throws errors in python3.5 (but not python3.6).
I will update the documentation to reflect this change to python version in another pull request.
Closes #82.
> Add support for python3.5

- docs/guide_to_saber_api.md
- docs/resources.md
- saber/cli/app.py
- saber/config.ini
- saber/config.py
- saber/constants.py
- saber/dataset.py
- saber/embeddings.py
- saber/saber.py
- saber/tests/resources/dummy_config.ini
- saber/tests/resources/dummy_constants.py
- saber/tests/resources/helpers.py
- saber/tests/test_config.py
- saber/tests/test_dataset.py
- saber/tests/test_embeddings.py
- saber/tests/test_saber.py
- saber/utils/app_utils.py
- saber/utils/data_utils.py
- saber/utils/grounding_utils.py
This pull request addresses #92. A user now has the option to load _all_ pre-trained embeddings, and not just those that appear in the training set. This is useful for deployment and transfer learning (as outlined in the issue).
This functionality is "off" by default and enabled with the `load_all_embeddings` argument (at the command line or in the config file) __or__ via the `load_all` argument in a call to `Saber.load_embeddings()`.
Closes #92.
> Load all embeddings

- .travis.yml
Builds on TravisCI were breaking for reasons I don't understand (the error message was very cryptic). Seems to be a problem with `msgpack` which is a dependency of SpaCy. The [solution](https://github.com/RasaHQ/rasa_nlu/issues/1563) was to downgrade `msgpack` in the build.
> Fixes build issue on TravisCI caused by msgpack issue

- README.md
Adding a Google Colaboratory link to readme. This allows a user to quickly try out Saber without installing anything locally.
In the future, it might be preferable for the notebook to be under version control. Sticking it in Google Drive was the fastest way to get the notebook up and running and should be fine for now.
Closes #104.
> Add Google Colaboratory link to readme

- saber/models/multi_task_lstm_crf.py
Updating loss function due to this warning: 
```
UserWarning: CRF.loss_function is deprecated and it might be removed in the future. Please use losses.crf_loss instead.
```
> Use new CRF loss function defined by keras-contrib

- docs/index.md
- docs/quick_start.md
- docs/resources.md
- saber/constants.py
- saber/preprocessor.py
- saber/saber.py
- saber/tests/test_data_utils.py
- saber/tests/test_dataset.py
- saber/tests/test_embeddings.py
- saber/tests/test_grounding_utils.py
- saber/tests/test_model_utils.py
- saber/tests/test_multi_task_lstm_crf.py
- saber/tests/test_saber.py
- saber/utils/app_utils.py
- saber/utils/grounding_utils.py
This pull request implements grounding/entity linking for the major entity classes (Chemicals/Drugs, Disease/Disorder, Species/Living beings, and Proteins/Genes) using the [EXTRACT 2.0 API](https://extract.jensenlab.org/). This is used in place of the grounding system we had previously, which only worked for protein/gene entities.
I tried to model the output format used by REACH as closely as possible. Grounding adds a new field to each item in `ents` (`xrefs`) in the output JSON returned by `Saber.annotate()`. E.g.,
_Without grounding_
```json
{
"text": "The phosphorylation of Hdm2 by MK2 promotes the ubiquitination of p53.",
"ents": [
{
"start": 23,
"end": 27,
"text": "Hdm2",
"label": "PRGE"
},
{
"start": 31,
"end": 34,
"text": "MK2",
"label": "PRGE"
},
{
"start": 66,
"end": 69,
"text": …
```
> Add grounding for major entity types using EXTRACT 2.0 API

- saber/models/bert_for_ner.py
The last pull request broke annotation with BERT based models. Fixed the issue by forcing placing the tensors returned by `predict()` onto the CPU.
> Put tensors returned under predict on CPU

- saber/metrics.py
- saber/models/bert_for_ner.py
- saber/models/bert_for_ner_and_re.py
- saber/tests/conftest.py
- saber/tests/test_saber.py
- saber/utils/model_utils.py
This pull request adds support for [mixed-precision training](https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html) to Saber two models. In short, NVIDIAs AMP library takes care of casting tensors to 16-bit precision, which reduces memory usage and speeds up training. In our case, I am seeing a roughly 23% reduction in training times. 
If `apex` is installed, it is used for mixed-precision training. Otherwise, the model is trained at regular 32-bit precision.
```python
try:
from apex import amp
model, optimizers = amp.initialize(self.model, optimizers, opt_level='O1')
LOGGER.info("Imported Apex. Training with mixed precision (opt_level='O1').")
except ImportError:
print(("Install Apex for faster training times and reduced memory usage"
" …
```
> Add support for mixed precision

- saber/metrics.py
- saber/preprocessor.py
- saber/tests/conftest.py
- saber/utils/bert_utils.py
- setup.py
This pull request is a bit of a stop-gap. The only remaining function we were using from the Keras / Tensorflow libraries was the `pad_sequence` utility. 
I have made `keras_preprocessing` a dependency, which allowed us to drop both `keras` and `tensorflow` as dependencies.
> Removing Keras / Tensorflow dependencies

- docs/resources.md
- saber/models/bert_for_ner.py
- saber/models/bert_for_ner_and_re.py
- saber/tests/conftest.py
- saber/tests/test_base_model.py
- saber/tests/test_bert_for_ner.py
- saber/tests/test_bert_for_ner_and_re.py
- saber/tests/test_data_utils.py
- saber/tests/test_embeddings.py
- saber/tests/test_metrics.py
- saber/utils/data_utils.py
Previously, only one of `k_folds` or `validation_split` could be used, with `k_folds` taking precedence over `validation_split`. Now, they can be used together.
- To use k-fold cross-validation, provide only a `train.*` file under `dataset_folder`. Choose the number of folds with the `k_folds` argument. Optionally, specify a proportion of examples to hold-out at random in each fold as a validation set with `validation_split`.
- To create a validation split from the train set, provide a `train.*` file (and optionally, a `test.*` file) under `dataset_folder` and specify the proportion of training examples to hold-out for a validation set with `validation_split`.
Otherwise, provide the partitions yourself with the files `train.*`, `valid.*` and `test.*` under `dataset_folder` and leave …
> Better use of validation split

- saber/constants.py
- saber/models/bert_for_ner.py
- saber/models/bert_for_ner_and_re.py
- saber/models/modules/bert_for_entity_and_relation_extraction.py
- saber/tests/test_bert_utils.py
- tox.ini
This pull request adds the missing transformer encoder layer to our joint NER + RE model ✨.  
Right now, the number of attention heads and the number of encoder layers are both hardcoded at 2. In future pull requests, these will be added to the config file and we will include them in our hyperparameter search to determine the best default values.
Trying to train on a CPU with Apex caused an error. This has been fixed by requiring both Apex and an available GPU before defaulting to mixed-precision training.
Closes #167.
> Implement transformer

- saber/__init__.py
Quick PR to fix all random seeds. 
The random seed is chosen with `saber.constants.RANDOM_STATE` (`42` by default). This value is used to seed the random number generators of pythons `random` module, `numpy`, and `torch`.
This will allow us to run multiple trials with different random seeds and then average them.
> Fix random seeds

- saber/models/bert_for_ner_and_re.py
- saber/models/modules/bert_for_entity_and_relation_extraction.py
- saber/models/modules/bert_for_token_classification_multi_task.py
- saber/tests/test_bert_utils.py
- saber/utils/bert_utils.py
- setup.py
This PR is a combination of a few things, just rolled them into one as we are rushing toward the ICLR deadline.
1. Replaces list comprehensions used to generate attention masks with `torch.where`. This is many times faster.
2. Remove the transformer layer. It was accounting for almost no performance (and actually hurting performance in some cases).
3. Clean up the optimizer initialization code. It is now better written to prevent weight decay being applied to normalization layers.
> Something funky happen and I had to push the same commits twice.
> Faster att mask gen

- saber/models/bert_for_ner_and_re.py
This PR implements entity pre-training. Simply put, entity pre-training involves pre-training the entity module before training the entire NER + RE model jointly.
Previously, we were implementing this by delaying the training of the RE module by a full epoch. I have found a different yet equally simple technique that works quite well. Basically, the loss function is weighted according to
```python
loss = ner_loss + decay_coef * re_loss
```
where `0 <= delay_coef <= 1` and is computed as  `current_step / total_steps` if this is the first epoch, or `1` otherwise. I saw gains up to 1% on the validation set using this scheme.
> Implements entity pre-training
